//! 主题数据结构 + 内置主题
//!
//! 内置:Vibe(自家原创默认)+ Catppuccin Mocha
//! 补全 10 套(Nord / Tokyo Night / GitHub Light / Solarized 等)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Theme {
    pub schema_version: u32,
    pub id: String,
    pub name: String,
    pub appearance: String, // "dark" | "light"
    pub author: String,
    pub shell: ThemeShell,
    pub terminal: ThemeTerminal,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeShell {
    pub background: String,
    pub surface: String,
    pub border: String,
    pub text_primary: String,
    pub text_secondary: String,
    pub accent: String,
    pub accent_subtle: String,
    pub status_running: String,
    pub status_waiting: String,
    pub status_idle: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeTerminal {
    pub background: String,
    pub foreground: String,
    pub cursor: String,
    pub selection_bg: String,
    pub black: String,
    pub red: String,
    pub green: String,
    pub yellow: String,
    pub blue: String,
    pub magenta: String,
    pub cyan: String,
    pub white: String,
    pub bright_black: String,
    pub bright_red: String,
    pub bright_green: String,
    pub bright_yellow: String,
    pub bright_blue: String,
    pub bright_magenta: String,
    pub bright_cyan: String,
    pub bright_white: String,
}

pub fn builtins() -> Vec<Theme> {
    // 顺序:Vibe 排首位作 default,其余按 1-9 列
    vec![
        vibe(),
        nord(),
        tokyo_night(),
        catppuccin_mocha(),
        catppuccin_latte(),
        solarized_dark(),
        solarized_light(),
        github_light(),
        one_dark_pro(),
        gruvbox(),
    ]
}

pub(crate) fn vibe() -> Theme {
    Theme {
        schema_version: 1,
        id: "vibe".into(),
        name: "Vibe".into(),
        appearance: "dark".into(),
        author: "Built-in".into(),
        shell: ThemeShell {
            background: "#0d0e14".into(),
            surface: "#161821".into(),
            border: "#252836".into(),
            text_primary: "#e6e8ed".into(),
            text_secondary: "#8b91a3".into(),
            accent: "#7c9cff".into(),
            accent_subtle: "#3e4a7a".into(),
            status_running: "#7cb3ff".into(),
            status_waiting: "#ffb86c".into(),
            status_idle: "#525569".into(),
        },
        terminal: ThemeTerminal {
            background: "#0d0e14".into(),
            foreground: "#e6e8ed".into(),
            cursor: "#7c9cff".into(),
            selection_bg: "#2a3050".into(),
            black: "#1a1c25".into(),
            red: "#ff6b81".into(),
            green: "#9eea6a".into(),
            yellow: "#ffd866".into(),
            blue: "#7c9cff".into(),
            magenta: "#c792ea".into(),
            cyan: "#62d6e8".into(),
            white: "#cfd2da".into(),
            bright_black: "#3a3d4a".into(),
            bright_red: "#ff7b91".into(),
            bright_green: "#aeea7a".into(),
            bright_yellow: "#ffe276".into(),
            bright_blue: "#8cacff".into(),
            bright_magenta: "#d7a2fa".into(),
            bright_cyan: "#72e6f8".into(),
            bright_white: "#e6e8ed".into(),
        },
    }
}

fn nord() -> Theme {
    Theme {
        schema_version: 1,
        id: "nord".into(),
        name: "Nord".into(),
        appearance: "dark".into(),
        author: "Built-in (based on nordtheme.com)".into(),
        shell: ThemeShell {
            background: "#2e3440".into(),
            surface: "#3b4252".into(),
            border: "#434c5e".into(),
            text_primary: "#eceff4".into(),
            text_secondary: "#d8dee9".into(),
            accent: "#88c0d0".into(),
            accent_subtle: "#5e81ac".into(),
            status_running: "#81a1c1".into(),
            status_waiting: "#ebcb8b".into(),
            status_idle: "#4c566a".into(),
        },
        terminal: ThemeTerminal {
            background: "#2e3440".into(),
            foreground: "#d8dee9".into(),
            cursor: "#d8dee9".into(),
            selection_bg: "#434c5e".into(),
            black: "#3b4252".into(),
            red: "#bf616a".into(),
            green: "#a3be8c".into(),
            yellow: "#ebcb8b".into(),
            blue: "#81a1c1".into(),
            magenta: "#b48ead".into(),
            cyan: "#88c0d0".into(),
            white: "#e5e9f0".into(),
            bright_black: "#4c566a".into(),
            bright_red: "#bf616a".into(),
            bright_green: "#a3be8c".into(),
            bright_yellow: "#ebcb8b".into(),
            bright_blue: "#81a1c1".into(),
            bright_magenta: "#b48ead".into(),
            bright_cyan: "#8fbcbb".into(),
            bright_white: "#eceff4".into(),
        },
    }
}

fn tokyo_night() -> Theme {
    Theme {
        schema_version: 1,
        id: "tokyo-night".into(),
        name: "Tokyo Night".into(),
        appearance: "dark".into(),
        author: "Built-in (based on enkia/tokyo-night)".into(),
        shell: ThemeShell {
            background: "#1a1b26".into(),
            surface: "#16161e".into(),
            border: "#292e42".into(),
            text_primary: "#c0caf5".into(),
            text_secondary: "#9aa5ce".into(),
            accent: "#7aa2f7".into(),
            accent_subtle: "#3d59a1".into(),
            status_running: "#7aa2f7".into(),
            status_waiting: "#e0af68".into(),
            status_idle: "#414868".into(),
        },
        terminal: ThemeTerminal {
            background: "#1a1b26".into(),
            foreground: "#c0caf5".into(),
            cursor: "#c0caf5".into(),
            selection_bg: "#33467c".into(),
            black: "#15161e".into(),
            red: "#f7768e".into(),
            green: "#9ece6a".into(),
            yellow: "#e0af68".into(),
            blue: "#7aa2f7".into(),
            magenta: "#bb9af7".into(),
            cyan: "#7dcfff".into(),
            white: "#a9b1d6".into(),
            bright_black: "#414868".into(),
            bright_red: "#f7768e".into(),
            bright_green: "#9ece6a".into(),
            bright_yellow: "#e0af68".into(),
            bright_blue: "#7aa2f7".into(),
            bright_magenta: "#bb9af7".into(),
            bright_cyan: "#7dcfff".into(),
            bright_white: "#c0caf5".into(),
        },
    }
}

fn catppuccin_latte() -> Theme {
    Theme {
        schema_version: 1,
        id: "catppuccin-latte".into(),
        name: "Catppuccin Latte".into(),
        appearance: "light".into(),
        author: "Built-in".into(),
        shell: ThemeShell {
            background: "#eff1f5".into(),
            surface: "#e6e9ef".into(),
            border: "#bcc0cc".into(),
            text_primary: "#4c4f69".into(),
            text_secondary: "#6c6f85".into(),
            accent: "#8839ef".into(),
            accent_subtle: "#ccd0da".into(),
            status_running: "#1e66f5".into(),
            status_waiting: "#df8e1d".into(),
            status_idle: "#9ca0b0".into(),
        },
        terminal: ThemeTerminal {
            background: "#eff1f5".into(),
            foreground: "#4c4f69".into(),
            cursor: "#dc8a78".into(),
            selection_bg: "#ccd0da".into(),
            black: "#5c5f77".into(),
            red: "#d20f39".into(),
            green: "#40a02b".into(),
            yellow: "#df8e1d".into(),
            blue: "#1e66f5".into(),
            magenta: "#ea76cb".into(),
            cyan: "#179299".into(),
            white: "#acb0be".into(),
            bright_black: "#6c6f85".into(),
            bright_red: "#d20f39".into(),
            bright_green: "#40a02b".into(),
            bright_yellow: "#df8e1d".into(),
            bright_blue: "#1e66f5".into(),
            bright_magenta: "#ea76cb".into(),
            bright_cyan: "#179299".into(),
            bright_white: "#bcc0cc".into(),
        },
    }
}

fn solarized_dark() -> Theme {
    Theme {
        schema_version: 1,
        id: "solarized-dark".into(),
        name: "Solarized Dark".into(),
        appearance: "dark".into(),
        author: "Built-in (Ethan Schoonover)".into(),
        shell: ThemeShell {
            background: "#002b36".into(),
            surface: "#073642".into(),
            border: "#586e75".into(),
            text_primary: "#fdf6e3".into(),
            text_secondary: "#93a1a1".into(),
            accent: "#268bd2".into(),
            accent_subtle: "#073642".into(),
            status_running: "#268bd2".into(),
            status_waiting: "#b58900".into(),
            status_idle: "#586e75".into(),
        },
        terminal: ThemeTerminal {
            background: "#002b36".into(),
            foreground: "#839496".into(),
            cursor: "#93a1a1".into(),
            selection_bg: "#073642".into(),
            black: "#073642".into(),
            red: "#dc322f".into(),
            green: "#859900".into(),
            yellow: "#b58900".into(),
            blue: "#268bd2".into(),
            magenta: "#d33682".into(),
            cyan: "#2aa198".into(),
            white: "#eee8d5".into(),
            bright_black: "#002b36".into(),
            bright_red: "#cb4b16".into(),
            bright_green: "#586e75".into(),
            bright_yellow: "#657b83".into(),
            bright_blue: "#839496".into(),
            bright_magenta: "#6c71c4".into(),
            bright_cyan: "#93a1a1".into(),
            bright_white: "#fdf6e3".into(),
        },
    }
}

fn solarized_light() -> Theme {
    Theme {
        schema_version: 1,
        id: "solarized-light".into(),
        name: "Solarized Light".into(),
        appearance: "light".into(),
        author: "Built-in (Ethan Schoonover)".into(),
        shell: ThemeShell {
            background: "#fdf6e3".into(),
            surface: "#eee8d5".into(),
            border: "#93a1a1".into(),
            text_primary: "#002b36".into(),
            text_secondary: "#586e75".into(),
            accent: "#268bd2".into(),
            accent_subtle: "#eee8d5".into(),
            status_running: "#268bd2".into(),
            status_waiting: "#b58900".into(),
            status_idle: "#93a1a1".into(),
        },
        terminal: ThemeTerminal {
            background: "#fdf6e3".into(),
            foreground: "#657b83".into(),
            cursor: "#586e75".into(),
            selection_bg: "#eee8d5".into(),
            black: "#073642".into(),
            red: "#dc322f".into(),
            green: "#859900".into(),
            yellow: "#b58900".into(),
            blue: "#268bd2".into(),
            magenta: "#d33682".into(),
            cyan: "#2aa198".into(),
            white: "#eee8d5".into(),
            bright_black: "#002b36".into(),
            bright_red: "#cb4b16".into(),
            bright_green: "#586e75".into(),
            bright_yellow: "#657b83".into(),
            bright_blue: "#839496".into(),
            bright_magenta: "#6c71c4".into(),
            bright_cyan: "#93a1a1".into(),
            bright_white: "#fdf6e3".into(),
        },
    }
}

fn github_light() -> Theme {
    Theme {
        schema_version: 1,
        id: "github-light".into(),
        name: "GitHub Light".into(),
        appearance: "light".into(),
        author: "Built-in (GitHub Primer)".into(),
        shell: ThemeShell {
            background: "#ffffff".into(),
            surface: "#f6f8fa".into(),
            border: "#d0d7de".into(),
            text_primary: "#1f2328".into(),
            text_secondary: "#656d76".into(),
            accent: "#0969da".into(),
            accent_subtle: "#ddf4ff".into(),
            status_running: "#0969da".into(),
            status_waiting: "#bf8700".into(),
            status_idle: "#8c959f".into(),
        },
        terminal: ThemeTerminal {
            background: "#ffffff".into(),
            foreground: "#24292f".into(),
            cursor: "#1f2328".into(),
            selection_bg: "#ddf4ff".into(),
            black: "#24292f".into(),
            red: "#cf222e".into(),
            green: "#116329".into(),
            yellow: "#4d2d00".into(),
            blue: "#0969da".into(),
            magenta: "#8250df".into(),
            cyan: "#1b7c83".into(),
            white: "#6e7781".into(),
            bright_black: "#57606a".into(),
            bright_red: "#a40e26".into(),
            bright_green: "#1a7f37".into(),
            bright_yellow: "#633c01".into(),
            bright_blue: "#218bff".into(),
            bright_magenta: "#a475f9".into(),
            bright_cyan: "#3192aa".into(),
            bright_white: "#8c959f".into(),
        },
    }
}

fn one_dark_pro() -> Theme {
    Theme {
        schema_version: 1,
        id: "one-dark-pro".into(),
        name: "One Dark Pro".into(),
        appearance: "dark".into(),
        author: "Built-in (Atom One Dark)".into(),
        shell: ThemeShell {
            background: "#282c34".into(),
            surface: "#21252b".into(),
            border: "#3e4451".into(),
            text_primary: "#abb2bf".into(),
            text_secondary: "#5c6370".into(),
            accent: "#61afef".into(),
            accent_subtle: "#3e4451".into(),
            status_running: "#61afef".into(),
            status_waiting: "#e5c07b".into(),
            status_idle: "#5c6370".into(),
        },
        terminal: ThemeTerminal {
            background: "#282c34".into(),
            foreground: "#abb2bf".into(),
            cursor: "#528bff".into(),
            selection_bg: "#3e4451".into(),
            black: "#282c34".into(),
            red: "#e06c75".into(),
            green: "#98c379".into(),
            yellow: "#e5c07b".into(),
            blue: "#61afef".into(),
            magenta: "#c678dd".into(),
            cyan: "#56b6c2".into(),
            white: "#abb2bf".into(),
            bright_black: "#5c6370".into(),
            bright_red: "#e06c75".into(),
            bright_green: "#98c379".into(),
            bright_yellow: "#e5c07b".into(),
            bright_blue: "#61afef".into(),
            bright_magenta: "#c678dd".into(),
            bright_cyan: "#56b6c2".into(),
            bright_white: "#ffffff".into(),
        },
    }
}

fn gruvbox() -> Theme {
    Theme {
        schema_version: 1,
        id: "gruvbox".into(),
        name: "Gruvbox".into(),
        appearance: "dark".into(),
        author: "Built-in (morhetz)".into(),
        shell: ThemeShell {
            background: "#282828".into(),
            surface: "#1d2021".into(),
            border: "#3c3836".into(),
            text_primary: "#ebdbb2".into(),
            text_secondary: "#a89984".into(),
            accent: "#fabd2f".into(),
            accent_subtle: "#504945".into(),
            status_running: "#83a598".into(),
            status_waiting: "#fabd2f".into(),
            status_idle: "#665c54".into(),
        },
        terminal: ThemeTerminal {
            background: "#282828".into(),
            foreground: "#ebdbb2".into(),
            cursor: "#ebdbb2".into(),
            selection_bg: "#504945".into(),
            black: "#282828".into(),
            red: "#cc241d".into(),
            green: "#98971a".into(),
            yellow: "#d79921".into(),
            blue: "#458588".into(),
            magenta: "#b16286".into(),
            cyan: "#689d6a".into(),
            white: "#a89984".into(),
            bright_black: "#928374".into(),
            bright_red: "#fb4934".into(),
            bright_green: "#b8bb26".into(),
            bright_yellow: "#fabd2f".into(),
            bright_blue: "#83a598".into(),
            bright_magenta: "#d3869b".into(),
            bright_cyan: "#8ec07c".into(),
            bright_white: "#ebdbb2".into(),
        },
    }
}

fn catppuccin_mocha() -> Theme {
    Theme {
        schema_version: 1,
        id: "catppuccin-mocha".into(),
        name: "Catppuccin Mocha".into(),
        appearance: "dark".into(),
        author: "Built-in".into(),
        shell: ThemeShell {
            background: "#1e1e2e".into(),
            surface: "#181825".into(),
            border: "#313244".into(),
            text_primary: "#cdd6f4".into(),
            text_secondary: "#a6adc8".into(),
            accent: "#cba6f7".into(),
            accent_subtle: "#585b70".into(),
            status_running: "#89b4fa".into(),
            status_waiting: "#f9e2af".into(),
            status_idle: "#45475a".into(),
        },
        terminal: ThemeTerminal {
            background: "#1e1e2e".into(),
            foreground: "#cdd6f4".into(),
            cursor: "#f5e0dc".into(),
            selection_bg: "#45475a".into(),
            black: "#45475a".into(),
            red: "#f38ba8".into(),
            green: "#a6e3a1".into(),
            yellow: "#f9e2af".into(),
            blue: "#89b4fa".into(),
            magenta: "#f5c2e7".into(),
            cyan: "#94e2d5".into(),
            white: "#bac2de".into(),
            bright_black: "#585b70".into(),
            bright_red: "#f38ba8".into(),
            bright_green: "#a6e3a1".into(),
            bright_yellow: "#f9e2af".into(),
            bright_blue: "#89b4fa".into(),
            bright_magenta: "#f5c2e7".into(),
            bright_cyan: "#94e2d5".into(),
            bright_white: "#a6adc8".into(),
        },
    }
}
