// 本文件由 Rust 类型自动生成 —— 不要手改。
// 重新生成:src-tauri 下 `VIBETERM_UPDATE_TS=1 cargo test --bin vibeterm ts_mirror`

// This file has been generated by Specta. DO NOT EDIT.

export type ActionEntry = { id: string; title: string; icon?: string | null; command: string; mode: ActionMode; shortcut?: string | null; close_on_success: boolean }

/**
 * 执行模式
 */
export type ActionMode = 
/**
 * 把 command 当作输入送到当前终端(自动追加 \n)
 */
"current_terminal" | 
/**
 * 新建一个 task 跑 command(继承当前 task 的 worktree?暂不;走 $HOME)
 */
"new_task" | 
/**
 * 仅插入 command 文本(不附加 \n,等同 prompt 插入)
 */
"insert"

export type ActionsFile = { schema_version: number; actions: ActionEntry[] }

export type ActiveBlock = { 
/**
 * block 起点 (unix ms), 向下取整到整点
 */
start_at_ms: number; 
/**
 * block 终点 = start + 5h
 */
end_at_ms: number; 
/**
 * 最后一条 entry 时间 (用来判断 active)
 */
last_entry_at_ms: number; 
/**
 * 已用的 token 之和 (input + cache_creation + cache_read + output)
 */
tokens_used: number; 
/**
 * 当前 block 已经过了多久 (now - start)
 */
elapsed_ms: number; 
/**
 * 剩余时间 (end - now), 已过期为 0
 */
remaining_ms: number; 
/**
 * 已用比 (elapsed / 5h × 100, 用作时间维度的进度条)
 */
elapsed_pct: number; 
/**
 * burn rate — 整个 block 平均 tokens / min
 */
tokens_per_min_avg: number; 
/**
 * burn rate — 最近 N 条 entry (N≈10) 的 tokens / min, 反映"当下速度"
 */
tokens_per_min_recent: number; 
/**
 * 等级 (匹配 ccusage 阈值): "normal" / "moderate" / "high"
 */
burn_rate_level: string; 
/**
 * block 内累计 cost (USD). 模型未匹配 pricing 表则为 None.
 * 注: 这是按 hardcoded pricing × tokens 估算, **不是 Anthropic 权威值**.
 * 仅保留字段方便未来按需重启, 当前 UI 不显示.
 */
cost_usd: number | null }

/**
 * 11 种 agent — 与 Prowl 对齐
 */
export type AgentKind = "pi" | "claude" | "codex" | "gemini" | "cursor" | "cline" | "opencode" | "copilot" | "kimi" | "droid" | "amp" | "aider"

/**
 * 统一的 agent 用量快照(provider 抽象输出)。
 */
export type AgentUsage = { kind: ProviderAgentKind; model: string | null; effort: string | null; context: ProviderContextUsage | null; quotas: ProviderQuotaWindow[]; cost_usd: number | null; 
/**
 * 降级链诊断
 */
sources: SourceAttempt[] }

/**
 * 软件版本检查结果(仅展示 + 给下载链接, 不下载安装).
 */
export type AppUpdateInfo = { current: string; latest: string | null; has_update: boolean; release_url: string | null; notes: string | null; published_at: string | null }

/**
 * `git worktree add` 的分支策略(IPC 层 mirror,与 vibeterm-git::BranchSpec 对齐)
 */
export type BranchSpecDto = { mode: "existing"; branch: string } | { mode: "new_from_head"; branch: string } | { mode: "new_from_ref"; branch: string; start_point: string }

/**
 * 自带声音库:从 bundle resources/sounds/sounds.json 读清单.
 * 前端下拉用 (按 category 分组). 找不到 manifest 返回空数组 (前端降级).
 */
export type BuiltinSound = { id: string; name: string; category: string; file: string }

/**
 * Session 级信息 — 由 v2 的 project transcript watcher 填充
 */
export type ClaudeSession = { session_id: string; project_path: string; model: string | null; 
/**
 * 当前 context 使用量 (input + cache_read + cache_creation, 不含 output)
 */
context_tokens: number | null; 
/**
 * 模型上下文窗口上限 (根据 model_id 查表)
 */
context_window: number | null; 
/**
 * 累计 cost (USD)
 */
session_cost_usd: number | null; 
/**
 * Prompt cache 5min TTL 到期时刻 (unix ms) — None = 没用过 5min cache.
 * Anthropic prompt cache 5m 跟 1h 是两个独立 TTL, 取最后一次 cache_creation
 * 写入时刻 + TTL 长度作为到期时刻. 后续 cache_read 命中不刷新 TTL.
 */
cache_5m_until_ms: number | null; 
/**
 * Prompt cache 1h TTL 到期时刻 (unix ms) — None = 没用过 1h cache.
 */
cache_1h_until_ms: number | null; 
/**
 * 最新一次 hook 回传 (transcript 里的 attachment.response) 携带的 reasoning effort
 * 等级 (`low` / `medium` / `high` / `xhigh` 等). Claude 仅在 hook 触发时把 effort
 * 写进 transcript, 没 hook / 没取到 → None (widget 不显, 不臆造).
 */
effort: string | null; 
/**
 * 最后一条 assistant 的 `stop_reason`:`"end_turn"` = 一轮答完(供完成检测),
 * `"tool_use"` = 中间步骤。None = 该格式无此字段(优雅降级,不臆造完成)。
 */
stop_reason: string | null; 
/**
 * 最后一条 assistant 顶层 `uuid` — 完成检测去重(同一轮 watcher 多次 emit 只标一次)。
 */
last_turn_id: string | null }

export type CliStatus = { name: string; installed: boolean; path: string | null }

/**
 * 粘贴图片临时落盘的位置 + 容量
 * 
 * - `dir`:绝对路径或 `~/...`;留空 → 用 config_dir 下 `clipboard-images/`
 * - `max_count`:文件数上限,留空 → 200
 * - `max_mb`:总字节上限(MB),留空 → 200
 * 
 * 全字段都不填等价于不写本 section,行为完全等同上一版本。
 */
export type ClipboardImagesSection = { dir?: string | null; max_count?: number | null; max_mb?: number | null }

export type CodexSnapshot = { session_id: string; cwd: string; model: string | null; model_provider: string | null; cli_version: string | null; 
/**
 * 当前 turn 的 total_tokens (跟 Codex CLI `tokens_in_context_window` 一致).
 */
context_tokens: number | null; context_window: number | null; 
/**
 * Context 占用百分比 — 严格按 Codex CLI 算法 (扣 BASELINE_TOKENS=12000).
 * 公式: (total_tokens - 12000) / (context_window - 12000) * 100, clamp 0..100.
 * 不算就 None (window 太小或缺数据). 前端 codex-ctx widget 直接用这个值,
 * 不要自己 ratio, 否则跟 Codex CLI 显示对不上.
 */
context_used_pct: number | null; 
/**
 * rate_limits.primary — Codex 主配额 (window_minutes / used_percent / resets_at)
 */
primary_limit: RateLimit | null; 
/**
 * rate_limits.secondary — 次配额 (一般是 5h 之类)
 */
secondary_limit: RateLimit | null; plan_type: string | null; updated_at_ms: number; 
/**
 * 最近几次 turn 的 tokens / min (用 token_count 事件时间戳算)
 */
tokens_per_min_recent: number; 
/**
 * "normal" / "moderate" / "high" — 跟 Claude 同阈值
 */
burn_rate_level: string; 
/**
 * 最新 turn 的 reasoning effort (`xhigh` / `high` / `normal` / `low`)
 */
effort: string | null; 
/**
 * 最近一条记录是否为 `task_complete` 事件(= codex 答完一轮,供完成检测)。
 */
task_completed: boolean; 
/**
 * 最后一个 `task_complete` 的去重标识(timestamp/序号)。
 */
last_turn_id: string | null }

export type Config = { schema_version: number; active_theme: string; follow_system_theme: boolean; language?: string | null; 
/**
 * zsh shell 集成自动注入(spawn 时临时 ZDOTDIR,让 OSC 133 标记可靠发出)。
 * 默认开;纯临时 env 注入,不写用户 dotfiles。
 */
shell_integration: boolean; 
/**
 * 启动时自动检查软件更新(默认开)。仅 GET GitHub latest release 比对版本号 —— 只读、
 * 不上传、零遥测、不自动下载安装。可在设置·更新页关闭(关闭后开箱完全不主动联网)。
 */
auto_check_updates: boolean }

export type CreateTaskOpts = { name: string; cwd: string | null; 
/**
 * 同时挂一个 worktree(可选)。携带时 task.cwd 会被覆盖为 worktree_path。
 */
worktree?: WorktreeRef | null }

export type DailyStat = { 
/**
 * 本地时区 `YYYY-MM-DD`.
 */
date: string; claude_tokens: number; codex_tokens: number; cost_usd: number | null }

/**
 * 重置所有快捷键为内置默认值. 删 keybindings.toml, 下次 load 返回 default.
 * 立即对指定 terminal 的 shell pid 做一次 agent 嗅探, 不等 3s 后台轮询.
 * PromptPicker 弹出时调一次, 确保 kind 与"用户当前焦点所在终端"一致.
 * 返回完整诊断信息: 命中的 agent + pid + pgid + 整个 process group cmdlines,
 * 前端 console 直接展示, 不需要后端日志.
 */
export type DetectAgentResult = { agent_kind: string | null; shell_pid: number | null; pgid: number | null; cmdlines: string[]; note: string }

export type EnvFile = { schema_version: number; env: Partial<{ [key in string]: string }>; proxy?: ProxySection | null; 
/**
 * 粘贴图片落盘配置(None / 全字段 None → 用代码默认)
 */
clipboard_images?: ClipboardImagesSection | null }

/**
 * 单个事件的通知偏好。
 */
export type EventNotifyPrefs = { enabled: boolean; 
/**
 * 系统声音名(macOS: Glass/Tink/Sosumi/Hero/Pop 等,或 `~/Library/Sounds/<name>.aiff`)。
 * 空字符串或 None → 走系统默认。
 */
sound?: string | null }

export type EventsPrefs = { waiting_input: EventNotifyPrefs; done: EventNotifyPrefs }

/**
 * 执行一个 action。
 * 
 * 模式:
 * - current_terminal: 写到指定 terminal_id(必传),自动追加 \n
 * - new_task: 创建新 task,命名 "<title>",cwd=$HOME,后台 spawn 由前端触发
 * (本命令只创建 task 并写回 command;前端拿 task_id 后 spawn + write)
 * - insert: 写到指定 terminal_id,不加 \n
 * 
 * 返回:
 * - current_terminal / insert → ExecuteActionResult::WrittenTo { terminal_id }
 * - new_task → ExecuteActionResult::NewTask { task_id, command }
 */
export type ExecuteActionResult = { kind: "written_to"; terminal_id: number } | { kind: "new_task"; task_id: number; command: string }

export type ExtraUsage = { is_enabled: boolean; monthly_limit: number | null; used_credits: number | null; utilization: number | null; currency: string | null; disabled_reason: string | null }

/**
 * 三源 diff 结果(借鉴 cmux diff-viewer 的 unstaged/staged/branch;**不含** agent-turn,那需 hook).
 */
export type GitDiffResult = { source: string; 
/**
 * VsRef 实际用的 base ref(自动推断时回填,供 UI 显示).
 */
base: string | null; 
/**
 * unified diff 原文(--no-color),前端解析渲染.
 */
raw: string; 
/**
 * 是否因超大被截断(防前端渲染卡死).
 */
truncated: boolean }

export type IpcError = { kind: "NotFound"; detail: { resource: string; id: string } } | { kind: "PermissionDenied"; detail: { reason: string } } | { kind: "PtySpawnFailed"; detail: { reason: string } } | { kind: "ConfigInvalid"; detail: { path: string; line: number; message: string } } | 
/**
 * panic 在 IPC handler 内被捕获 / 未分类错误。trace_id 关联日志。
 */
{ kind: "Unknown"; detail: { trace_id: string } }

export type KeybindingEntry = { command: string; keys: string; when?: string | null }

export type KeybindingsFile = { schema_version: number; bindings: KeybindingEntry[] }

/**
 * 一个 pane:可选启动命令 + 相对上一个 pane 的分屏方向 + 可选 cwd。
 */
export type LayoutPane = { 
/**
 * 终端就绪后自动发送的命令(末尾自动补换行)。空 = 纯终端不发命令。
 */
command?: string | null; 
/**
 * 相对上一个 pane 的分屏方向:"h"(右)| "v"(下)。第一个 pane 忽略。默认 "h"。
 */
split?: string | null; 
/**
 * 该 pane 的工作目录(相对 / 绝对)。给定时命令前缀 `cd <cwd> &&`。
 */
cwd?: string | null }

/**
 * 一个布局模板。
 */
export type LayoutTemplate = { name: string; 
/**
 * 命令面板模糊搜索关键词。
 */
keywords: string[]; 
/**
 * 任务工作目录(留空 = 默认 ~)。
 */
cwd?: string | null; panes: LayoutPane[] }

export type ModelStat = { model: string; total_tokens: number; 
/**
 * 该模型估算成本; 无定价 (Codex / 未知模型) 则 None.
 */
cost_usd: number | null; message_count: number }

export type NotifyFile = { schema_version: number; 
/**
 * 全局总开关。off 时所有通知一律不弹。
 */
enabled: boolean; events: EventsPrefs; quiet_hours: QuietHours; 
/**
 * 主窗口在前台、但完成的不是当前选中任务时,仍轻提示(前端音效 + 任务列表行高亮,
 * 不弹系统横幅 —— macOS 前台横幅本就常被吞)。关 → 维持"前台一律静默"。默认开。
 */
notify_focused_other_task: boolean; 
/**
 * Dock 图标角标显示"未看完成数"(聚合状态 = Done 的任务数),用户切到该任务后自动减一。
 * 安静的持续提醒,不响铃、不弹横幅,复用现有 seen/Done 模型。默认开。
 */
dock_badge_unseen: boolean; 
/**
 * 间歇持续声音提醒:只要有"未看完成"任务且主窗口未聚焦,就每隔 PERSISTENT_REMIND 秒响
 * **1 路**声音催用户回来看,直到未看完成数归零(全局单路,多任务不叠加)。打扰性最强,
 * 仅特定场景(离机跑长任务)需要,默认关。一旦主窗口聚焦即停 —— 人回到 app 就不再催。
 */
persistent_unseen_sound: boolean; 
/**
 * 持续提醒的响铃间隔(秒)。默认 30。仅 `persistent_unseen_sound` 开时生效;用时 clamp 到 [5,3600]。
 */
persistent_remind_secs: number }

/**
 * 声音预览/播放数据. bytes 为 base64 (避免 Vec<u8> 走 JSON 数字数组的 6× 膨胀).
 */
export type NotifySoundData = { 
/**
 * 音频 MIME (audio/aiff, audio/wav, audio/mpeg, audio/ogg, audio/mp4, ...).
 */
mime: string; 
/**
 * 原始音频字节的 base64.
 */
base64: string }

export type Orientation = "h" | "v"

/**
 * 当前价格来源状态 — 给设置·更新页显示.
 */
export type PricingStatus = { 
/**
 * "builtin" | "override"
 */
source: string; 
/**
 * override 表的 updated_at (builtin 时 None)
 */
updated_at: string | null; 
/**
 * override 表的 source 描述 (builtin 时 None)
 */
origin: string | null }

/**
 * 一个 profile = 一个终端模式的状态栏.
 * key 在 file 层是 HashMap 的 key (例如 `default` / `claude` / `codex`),
 * display_name 是 UI 显示用的中文标签 (可选).
 */
export type ProfileConfig = { 
/**
 * UI 显示名 (例如 "终端" / "Claude" / "Codex"). 缺省用 key.
 */
display_name?: string | null; 
/**
 * widget 列表, 数组顺序 = 显示顺序
 */
items: StatusLineItem[] }

export type ProjectStat = { project_path: string; total_tokens: number; cost_usd: number | null; message_count: number }

export type PromptEntry = { id: string; 
/**
 * 显示名. 内置预设的 i18n key 是 `prompts.preset.<id>.name`, 前端先查 i18n,
 * 找不到再 fallback 到此 name. 用户自定义的 prompt 不会撞 i18n key, 直接用 name.
 */
name: string; content: string; 
/**
 * 旧 prompts.toml 没此字段时按 "agent" 处理 (历史 prompt 都是给 agent 的).
 */
kind: PromptKind; shortcut?: string | null }

/**
 * 区分两类 prompt
 * - Agent: 给 LLM agent (claude / codex / aider 等) 的提问片段, 自然语言
 * - Terminal: 给 shell (zsh / bash) 的命令片段, 通常含 cursor 占位让用户调参
 * 
 * Picker 根据当前 task 的 agent_kind 自动过滤显示哪一类.
 */
export type PromptKind = "agent" | "terminal"

export type PromptsFile = { schema_version: number; prompts: PromptEntry[] }

export type ProviderAgentKind = "claude" | "codex"

/**
 * 会话 context 占用(统一)。`window` 拿不到时 `used_pct` 为 None → 前端显 "—"(不臆造)。
 */
export type ProviderContextUsage = { used_tokens: number | null; window: number | null; used_pct: number | null; 
/**
 * 窗口值来源(诊断用): "rollout"(Codex 权威) / "model-table"(Claude 前缀表兜底) / "none"
 */
window_source: string }

/**
 * 额度窗口(统一; 角色靠 `window_minutes` 判, 不靠 primary/secondary 位置)。
 */
export type ProviderQuotaWindow = { 
/**
 * "5h" / "7d" / "weekly" 等
 */
label: string; used_pct: number; window_minutes: number | null; 
/**
 * unix 秒; 拿不到为 None
 */
resets_at: number | null }

export type ProxySection = { enabled: boolean; http?: string | null; https?: string | null; no_proxy?: string | null }

/**
 * 免打扰时段。start/end 为 24h "HH:MM";start > end 表示跨夜。
 */
export type QuietHours = { enabled: boolean; start: string; end: string }

export type QuotaWindow = { 
/**
 * 0..=100, 服务端给的已用百分比
 */
utilization: number; 
/**
 * ISO8601 (UTC); 注意 Claude 文件里可能是 null
 */
resets_at: string | null }

export type RateLimit = { used_percent: number; 
/**
 * 窗口长度 (分钟) — 10080 = 7 天, 300 = 5 小时.
 * 上游 Codex 协议是 Option (free 计划 / 新模型常为 null), 必须容错:
 * 否则 null 会让整条 token_count 反序列化失败, 连 context_window 一起丢。
 */
window_minutes?: number | null; 
/**
 * unix seconds — 上游可能为 null → Option
 */
resets_at?: number | null }

/**
 * agent 会话恢复命令(Y1–Y3 的零侵入版)。
 * 🟢 只读嗅探 session_id(复用 read_for_cwd,不写任何 agent 配置、无 hook),据此构造 agent 原生
 * resume 命令字符串返回给前端。**不自动执行** —— 由用户在命令面板手动点"恢复 agent",
 * 前端再开一个新 pane 跑这条命令。无 cmux 那套签名审批信任模型(命令由 VibeTerm 内部构造 +
 * 用户手动触发,非外部进程提议,无需防伪)。
 */
export type ResumeInfo = { agent: string; session_id: string; command: string }

/**
 * 降级链单步诊断 —— 接 /doctor, 让"走了哪个源 / 为何降级"可见。
 */
export type SourceAttempt = { 
/**
 * "transcript" / "usage_cache.json" / "rollout" / "model-table" 等
 */
source: string; ok: boolean; note: string }

export type SpawnPtyOpts = { rows: number; cols: number; cwd: string | null; command: string | null; args: string[] | null; env: ([string, string])[] | null }

export type SpawnPtyResult = { terminal_id: number; 
/**
 * slot 幂等命中、attach 共享 PTY 时为 Some(订阅 id):前端组件卸载时据此 detach,
 * 否则浮窗每次开关都给共享 PTY 永久多挂一个 sink。全新 spawn 为 None(初始
 * sink 是状态嗅探主 sink,随 PTY 生命周期存续,不可 detach)。
 */
sink_id: number | null }

/**
 * 分屏树 mirror(前端 ui-core/src/split TS 类型 1:1 对应)
 */
export type SplitNode = { kind: "leaf"; slot_id: number } | { kind: "split"; orientation: Orientation; children: SplitNode[]; ratios?: number[] | null }

export type StatusLineFile = { schema_version: number; 
/**
 * 主题色开关
 */
use_theme_colors: boolean; 
/**
 * profile 映射. key 跟 agent_kind 对齐 (`default` 用作未识别 agent 的 fallback).
 */
profiles: Partial<{ [key in string]: ProfileConfig }>; 
/**
 * v1 旧字段, 迁移用. 新写不会输出.
 */
items?: StatusLineItem[] | null }

/**
 * 一个状态栏 widget 项 (同 v1).
 */
export type StatusLineItem = string | StatusLineItemDetail

export type StatusLineItemDetail = { type: string; color?: string | null; bold?: boolean | null; max_width?: number | null; hide?: boolean | null; metadata: Partial<{ [key in string]: string }> }

export type TaskDto = { id: number; name: string; cwd: string | null; pinned: boolean; status: TaskStatus; terminal_ids: number[]; 
/**
 * 任务在哪显示("main" / "floating-<label>" / "nowhere")
 */
location: TaskLocation; 
/**
 * 任务的分屏布局,后端为 source of truth,主 + 浮窗都读它。
 * 老 tasks.json 没此字段时 default singleLeaf(0)。
 */
split_tree: SplitNode; 
/**
 * Git worktree 挂载(可选,L1)。挂载后 PTY cwd = worktree_path。
 */
worktree?: WorktreeRef | null; 
/**
 * 识别到的 agent(从前台进程扫出来,周期刷新)
 */
agent_kind?: string | null; 
/**
 * 终端最新输出末行(任务名下显示一行 Prowl 风格状态)。
 * 不持久化到 tasks.json,emit_tasks_changed 时实时填充。
 */
last_output?: string | null; 
/**
 * 通知静音. true 时该 task 不弹系统通知 (持久化到 tasks.json).
 */
notify_muted: boolean; 
/**
 * hook: agent 当前 permission mode (claude/codex hook 携带).
 * "default" | "acceptEdits" | "plan" | "dontAsk" | "bypassPermissions". None = 未知.
 */
permission_mode?: string | null; 
/**
 * agent 当前 reasoning effort 等级 (low/medium/high/xhigh/max). None = 未知.
 * 来源:嗅探 claude 工作动画 "thinking with <effort> effort"(零侵入)。
 */
effort?: string | null }

export type TaskLocation = { kind: "Nowhere" } | { kind: "MainWorkspace" } | { kind: "Floating"; label: string }

export type TaskStatus = "idle" | "running" | "waiting_input" | 
/**
 * agent/命令"完成但用户未看"。语义层:
 * 当所有终端归于 idle 且该 task 不是当前 active main 时,聚合状态 = Done。
 * 用户切到该 task 后转回 Idle。
 */
"done" | 
/**
 * agent 在 Running 状态超过 stall_threshold_ms (默认 5 分钟) 无任何输出,
 * 且进程层识别为 agent_kind.is_some()(普通 shell 命令不打这个标)。
 * 通常是 agent 卡死 / 网络挂了 / 等待用户但 prompt 没识别出来.
 * 触发系统通知,用户可点回看。
 */
"stalled"

export type Theme = { schema_version: number; id: string; name: string; appearance: string; author: string; shell: ThemeShell; terminal: ThemeTerminal }

export type ThemeShell = { background: string; surface: string; border: string; text_primary: string; text_secondary: string; accent: string; accent_subtle: string; status_running: string; status_waiting: string; status_idle: string }

export type ThemeTerminal = { background: string; foreground: string; cursor: string; selection_bg: string; black: string; red: string; green: string; yellow: string; blue: string; magenta: string; cyan: string; white: string; bright_black: string; bright_red: string; bright_green: string; bright_yellow: string; bright_blue: string; bright_magenta: string; bright_cyan: string; bright_white: string }

export type Totals = { input_tokens: number; output_tokens: number; cache_creation_tokens: number; cache_read_tokens: number; 
/**
 * Claude 总 token.
 */
claude_tokens: number; 
/**
 * Codex 总 token.
 */
codex_tokens: number; 
/**
 * Claude 估算总成本 (USD). 无任何可定价条目则 None.
 */
cost_usd: number | null; 
/**
 * 模型未匹配定价表的 Claude 条目数 — UI 据此提示"成本含 N 条未计价".
 */
cost_unknown_entries: number; 
/**
 * 计入的 Claude 消息数 (去重后).
 */
message_count: number }

/**
 * `~/.claude/usage_cache.json` 完整反序列化结构
 */
export type UsageCache = { five_hour: QuotaWindow | null; seven_day: QuotaWindow | null; 
/**
 * Sonnet 独占 7d 配额 (付费/分级用户)
 */
seven_day_sonnet: QuotaWindow | null; 
/**
 * Opus 独占 7d 配额
 */
seven_day_opus: QuotaWindow | null; seven_day_oauth_apps: QuotaWindow | null; extra_usage: ExtraUsage | null }

/**
 * 聚合总览.
 */
export type UsageStats = { 
/**
 * 统计窗口 (天).
 */
range_days: number; 
/**
 * 生成时刻 unix ms.
 */
generated_at_ms: number; totals: Totals; 
/**
 * 按本地日期升序.
 */
daily: DailyStat[]; 
/**
 * 按 token 降序.
 */
by_model: ModelStat[]; 
/**
 * 按 token 降序.
 */
by_project: ProjectStat[] }

/**
 * 任务挂载的 git worktree 信息(L1)。
 * `head/is_dirty/ahead/behind/status_updated_at` 由后台轮询刷新。
 */
export type WorktreeRef = { 
/**
 * 主仓库 toplevel(用于 `git worktree` 命令的 cwd)
 */
repo_path: string; 
/**
 * worktree 实际路径(也是 PTY cwd)
 */
worktree_path: string; 
/**
 * 当前分支(detached 时为 None)
 */
branch: string | null; 
/**
 * HEAD commit sha(可能为空,首次未刷新时)
 */
head: string; is_dirty: boolean; ahead: number; behind: number; 
/**
 * 上次状态刷新的 unix ms(0 = 从未刷新)
 */
status_updated_at: number }

/**
 * 工作树状态(由 `git status --porcelain=v2 --branch` 解析)
 */
export type WorktreeStatus = { branch: string | null; head: string; is_dirty: boolean; ahead: number; behind: number; 
/**
 * 已 stage 的文件数 (index 中变更)
 */
staged: number; 
/**
 * 已修改未 stage 的文件数 (worktree 变更)
 */
unstaged: number; 
/**
 * 未跟踪文件数
 */
untracked: number }

